### ISSUE TITLE
npm build error within .pipeline

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/bcdk#11]
stack 
```shell
 DEBUG=* npm run build -- --pr=0 --dev-mode=true

> pipeline@1.0.0 build /Users/psimonia/gworkspace/bcdk-prac/.jenkins/.pipeline
> node build.js "--pr=0" "--dev-mode=true"

  trace:OpenShiftClient > oc --namespace=ocp101-tools process -f /Users/psimonia/gworkspace/bcdk-prac/.jenkins/openshift/build-master.yaml --param=NAME=jenkins-ps --param=SUFFIX=-build-0 --param=VERSION=build-1.0.0-0 --param=SOURCE_REPOSITORY_URL= --param=SOURCE_REPOSITORY_REF=refs/pull/0/head --output=json +0ms
  info:OpenShiftClient oc --namespace=ocp101-tools process -f /Users/psimonia/gworkspace/bcdk-prac/.jenkins/openshift/build-master.yaml --param=NAME=jenkins-ps --param=SUFFIX=-build-0 --param=VERSION=build-1.0.0-0 --param=SOURCE_REPOSITORY_URL= --param=SOURCE_REPOSITORY_REF=refs/pull/0/head --output=json  # (1) [0s] +0ms
/Users/psimonia/gworkspace/bcdk-prac/.jenkins/.pipeline/node_modules/pipeline-cli/lib/OpenShiftClient.js:167
      throw new Error(`command: ${['oc'].concat(args).join(' ')}\nstderr:${proc.stderr}`)
      ^

Error: command: oc --namespace=ocp101-tools process -f /Users/psimonia/gworkspace/bcdk-prac/.jenkins/openshift/build-master.yaml --param=NAME=jenkins-ps --param=SUFFIX=-build-0 --param=VERSION=build-1.0.0-0 --param=SOURCE_REPOSITORY_URL= --param=SOURCE_REPOSITORY_REF=refs/pull/0/head --output=json
stderr:error: unable to process template
  Required value: template.parameters[5]: parameter SOURCE_REPOSITORY_URL is required and must be specified

    at OpenShiftClientX._action (/Users/psimonia/gworkspace/bcdk-prac/.jenkins/.pipeline/node_modules/pipeline-cli/lib/OpenShiftClient.js:167:13)
    at OpenShiftClientX.process (/Users/psimonia/gworkspace/bcdk-prac/.jenkins/.pipeline/node_modules/pipeline-cli/lib/OpenShiftClient.js:338:23)
    at OpenShiftClientX.processDeploymentTemplate (/Users/psimonia/gworkspace/bcdk-prac/.jenkins/.pipeline/node_modules/pipeline-cli/lib/OpenShiftClientX.js:482:24)
    at module.exports (/Users/psimonia/gworkspace/bcdk-prac/.jenkins/.pipeline/lib/build.js:13:22)
    at Object.<anonymous> (/Users/psimonia/gworkspace/bcdk-prac/.jenkins/.pipeline/build.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

```

**Comment by cvarjao** [comment]
This was fixed with bcdevops/pipeline-cli@6f85a5b726499be31412ff5d533f95091096bf60
