### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by david-kerins** [BCDevOps/bcdk#84]
Sporadic deployment failures with the following error log.  Redeployment usually succeeds.

/var/lib/jenkins/jenkins-build-prod-1-r97lx/workspace/rsbc-dh_PR-5/.pipeline/node_modules/@bcgov/pipeline-cli/lib/OpenShiftClientResult.js:50
      .trim()
       ^

TypeError: Cannot read property 'trim' of undefined
    at Function.parseGetObjectValues (/var/lib/jenkins/jenkins-build-prod-1-r97lx/workspace/rsbc-dh_PR-5/.pipeline/node_modules/@bcgov/pipeline-cli/lib/OpenShiftClientResult.js:50:8)
    at Socket.proc.stdout.on (/var/lib/jenkins/jenkins-build-prod-1-r97lx/workspace/rsbc-dh_PR-5/.pipeline/node_modules/@bcgov/pipeline-cli/lib/OpenShiftClientResult.js:100:48)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by ychung-mot** [comment]
Any update on this? After the OCP4 upgrade, I see this more often.

**Comment by claregallan** [comment]
connecting thread from [Rocket Chat](https://chat.developer.gov.bc.ca/channel/devops-how-to/thread/T3qrTFEEpdrHGEnCD?jump=Jm3pJqNLvDksMsNzr) - BCDK is no longer supported.
